### ISSUE TITLE
bluetooth

### ISSUE THREAD

**Issue by childsummer** [zaoqi/kual-linuxdeploy-armhf#4]
能增加蓝牙模块么，这样可以连接蓝牙键盘之类？

**Comment by zaoqi** [comment]
建议在 mobileread 论坛询问。

**Comment by childsummer** [comment]
哈，我在那里翻了好几天帖子了，甚至也装了那个alpine。也有人提出来通过蓝牙外接设备，但由于azn没开放，似乎没人在做。看来看去，就觉得你这有希望。

**Comment by zaoqi** [comment]
而我不再用kindle了
